### ISSUE TITLE
Détection mouvement Voiture / personne

### ISSUE THREAD

**Issue by techno-blogger** [Jezza34000/reolink#21]
Bonjour,
  Un **grand merci** pour le plugin Reolink qui aide grandement à intégrer les caméras à Jeedom.
  
  je voulais vous faire une demande, ce serai d'ajouter la détection de mouvement de type voiture ou personne.

  Actuellement j'ai ajouté du code afin de lire l'API reolink :
  `http://IP/cgi-bin/api.cgi?cmd=GetAiState&rs=&user=xx&password=xx`

  Ceci me permet d'obtenir le JSON suivant 
`[ { "cmd" : "GetAiState", "code" : 0, "value" : { "channel" : 0, "face" : { "alarm_state" : 0, "support" : 0 }, "people" : { "alarm_state" : 0, "support" : 1 }, "vehicle" : { "alarm_state" : 0, "support" : 1 } } } ] `

  Mais je constate que entre la détection d'un mouvement et la lecture du JSON je perd l'information du type de détection surtout pour les voitures car c'est trop rapide pour le script.
  je pense donc que la solution est d'intégrer au plugin la détection AI.

  Pensez-vous que cela soit possible à intégrer au plugin ?
Merci d'avance

**Comment by techno-blogger** [comment]
Bon, je me trouve bête car je viens de voir que la branche beta à cette option.

**Comment by Jezza34000** [comment]
Yes d'ailleurs je viens de faire le PR sur la version STABLE  👍 
Si tu étais en BETA tu peux rebasculer sur la version stable

**Comment by techno-blogger** [comment]
Bonjour,
  J'ai regardé le code de la branche beta c'est comme ca que j'ai vu l'information.
  J'ai mis à jour le plugin en version du 18/10 mais je ne retrouve pas la détection des personnes ou véhicule.
  En regardant le reolinkapicmd.json je retrouve la notion de Délai Alarme Véhicule ou Personne ce qui n'utilise pas GetAiState

  il y a bien les variables MdPersonState et MdVehicleState qui utilise GetAiState mais pas je n'arrive pas à trouver où elles sont ensuite.

  Je pense que j'ai du mal comprendre le code.

**Comment by Jezza34000** [comment]
Hello,
Je ne sais pas trop a vrai dire. 
Pour ma part j'ai pas de caméra AI donc je ne peux pas faire de test, et je n'avais pas l'intention de developper cette partie pour plusieurs raisons : 
1- Je suis en train de quitter Jeedom pour migrer vers HomeAssistant
2- En developpant ce plugin je me suis apercu que ces caméras manque de faibilité et ont plein de bug dans l'API.
Du coup c'est @mnpg qui s'est occupé de cette feature, je pense qu'il pourra plus te répondre que moi sur l'état de ses travaux sur ce sujet...
